### ISSUE TITLE
Query DSL

### ISSUE THREAD

**Issue by kod-kristoff** [spraakbanken/karp-backend#27]
#### `freetext`
- [x] `freetext|<string>`
- [x] `freetext|<integer>`
- [x] `freetext||and|<string1>|<string2>`
- [x] `freetext||or|<string1>|<string2>`
- [x] `freetext||not|<string>`
- [x] `freetext||not|<string1>|<string2>`
#### `freergxp`
- [x] `freergxp|<regex>`
- [x] `freergxp||and|<regex1>|<regex2>`
- [x] `freergxp||or|<regex1>|<regex2>`
- [x] `freergxp||not|<regex>`
#### `exists`
- [x] `exists|<string>`
- [x] `exists||and|<string1>|<string2>`
- [x] `exists||or|<string1>|<string2>`
- [x] `exists||not|<string>`
#### `missing`
- [x] `missing|<string>`
- [x] `missing||and|<string1>|<string2>`
- [x] `missing||or|<string1>|<string2>`
- [x] `missing||not|<string>`
#### `equals`
- [x] `equals|<string>|<any>`
- [x] `equals||and|<string1>|<string2>||<string3>`
- [ ] `equals||and|<string1>|<string2>||and|<string3>|<string4>`
- [ ] `equals||and|<string1>|<string2>||or|<string3>|<string4>`
- [ ] `equals||and|<string1>|<string2>||not|<string3>`
- [x] `equals||or|<string1>|<string2>||<string3>`
- [ ] `equals||or|<string1>|<string2>||and|<string3>|<string4>`
- [ ] `equals||or|<string1>|<string2>||or|<string3>|<string4>`
- [ ] `equals||or|<string1>|<string2>||not|<string3>`
- [ ] `equals||not|<string1>||<string2>` See #123
- [ ] `equals||not|<string1>||and|<string2>|<string3>`
- [ ] `equals||not|<string1>||or|<string2>|<string3>`
- [ ] `equals||not|<string1>||not|<string2>`
- [x] `equals|<string1>||and|<string2>|<string3>`
- [x] `equals|<string1>||or|<string2>|<string3>`
- [x] `equals|<string1>||not|<string2>`
#### `regexp`
- [x] `regexp|<string>|<regex>`
- [x] `regexp||and|<string1>|<string2>||<regex1>`
- [ ] `regexp||and|<string1>|<string2>||and|<regex1>|<regex2>`
- [ ] `regexp||and|<string1>|<string2>||or|<regex1>|<regex2>`
- [ ] `regexp||and|<string1>|<string2>||not|<regex1>`
- [x] `regexp||or|<string1>|<string2>||<regex1>`
- [ ] `regexp||or|<string1>|<string2>||and|<regex1>|<regex2>`
- [ ] `regexp||or|<string1>|<string2>||or|<regex1>|<regex2>`
- [ ] `regexp||or|<string1>|<string2>||not|<regex1>`
- [ ] `regexp||not|<string>||<regex>` See #123
- [ ] `regexp||not|<string>||and|<regex1>|<regex2>`
- [ ] `regexp||not|<string>||or|<regex1>|<regex2>`
- [ ] `regexp||not|<string>||not|<regex>`
- [x] `regexp|<string>||and|<regex1>|<regex2>`
- [x] `regexp|<string>||or|<regex1>|<regex2>`
- [x] `regexp|<string>||not|<regex>`
#### `contains`
- [x] `contains|<string>|<string>`
- [x] `contains||and|<string1>|<string2>||<string3>`
- [ ] `contains||and|<string1>|<string2>||and|<string3>|<string4>`
- [ ] `contains||and|<string1>|<string2>||or|<string3>|<string4>`
- [ ] `contains||and|<string1>|<string2>||not|<string3>`
- [x] `contains||or|<string1>|<string2>||<string3>`
- [ ] `contains||or|<string1>|<string2>||and|<string3>|<string4>`
- [ ] `contains||or|<string1>|<string2>||or|<string3>|<string4>`
- [ ] `contains||or|<string1>|<string2>||not|<string3>`
- [ ] `contains||not|<string1>||<string2>` See #123
- [ ] `contains||not|<string1>||and|<string2>|<string3>`
- [ ] `contains||not|<string1>||or|<string2>|<string3>`
- [ ] `contains||not|<string1>||not|<string2>`
- [x] `contains|<string1>||and|<string2>|<string3>`
- [x] `contains|<string1>||or|<string2>|<string3>`
- [x] `contains|<string1>||not|<string2>`
#### `startswith`
- [x] `startswith|<string>|<string>`
- [x] `startswith||and|<string1>|<string2>||<string3>`
- [ ] `startswith||and|<string1>|<string2>||and|<string3>|<string4>`
- [ ] `startswith||and|<string1>|<string2>||or|<string3>|<string4>`
- [ ] `startswith||and|<string1>|<string2>||not|<string3>`
- [x] `startswith||or|<string1>|<string2>||<string3>`
- [ ] `startswith||or|<string1>|<string2>||and|<string3>|<string4>`
- [ ] `startswith||or|<string1>|<string2>||or|<string3>|<string4>`
- [ ] `startswith||or|<string1>|<string2>||not|<string3>`
- [ ] `startswith||not|<string1>||<string2>` See #123
- [ ] `startswith||not|<string1>||and|<string2>|<string3>`
- [ ] `startswith||not|<string1>||or|<string2>|<string3>`
- [ ] `startswith||not|<string1>||not|<string2>`
- [x] `startswith|<string1>||and|<string2>|<string3>`
- [x] `startswith|<string1>||or|<string2>|<string3>`
- [x] `startswith|<string1>||not|<string2>`
#### `endswith`
- [x] `endswith|<string>|<string>`
- [x] `endswith||and|<string1>|<string2>||<string3>`
- [ ] `endswith||and|<string1>|<string2>||and|<string3>|<string4>`
- [ ] `endswith||and|<string1>|<string2>||or|<string3>|<string4>`
- [ ] `endswith||and|<string1>|<string2>||not|<string3>`
- [x] `endswith||or|<string1>|<string2>||<string3>`
- [ ] `endswith||or|<string1>|<string2>||and|<string3>|<string4>`
- [ ] `endswith||or|<string1>|<string2>||or|<string3>|<string4>`
- [ ] `endswith||or|<string1>|<string2>||not|<string3>`
- [ ] `endswith||not|<string1>||<string2>` See #123
- [ ] `endswith||not|<string1>||and|<string2>|<string3>`
- [ ] `endswith||not|<string1>||or|<string2>|<string3>`
- [ ] `endswith||not|<string1>||not|<string2>`
- [x] `endswith|<string1>||and|<string2>|<string3>`
- [x] `endswith|<string1>||or|<string2>|<string3>`
- [x] `endswith|<string1>||not|<string2>`
#### `lt`
- [ ] `lt|<string>|<any>`
- [x] `lt|<string>|<integer>`
- [x] `lt|<string>|<string>`
- [x] `lt||and|<string1>|<string2>||<integer>`
- [x] `lt||and|<string1>|<string2>||<string>`
- [x] `lt||or|<string1>|<string2>||<integer>`
- [x] `lt||or|<string1>|<string2>||<string>`
- [ ] `lt||not|<string>||<integer>`
- [ ] `lt||not|<string>||<string>`
#### `lte`
- [ ] `lte|<string>|<any>`
- [x] `lte|<string>|<integer>`
- [x] `lte|<string>|<string>`
- [x] `lte||and|<string1>|<string2>||<integer>`
- [x] `lte||and|<string1>|<string2>||<string>`
- [x] `lte||or|<string1>|<string2>||<integer>`
- [x] `lte||or|<string1>|<string2>||<string>`
- [ ] `lte||not|<string>||<integer>`
- [ ] `lte||not|<string>||<string>`
#### `gt`
- [ ] `gt|<string>|<any>`
- [x] `gt|<string>|<integer>`
- [x] `gt|<string>|<string>`
- [x] `gt||and|<string1>|<string2>||<integer>`
- [x] `gt||and|<string1>|<string2>||<string>`
- [x] `gt||or|<string1>|<string2>||<integer>`
- [x] `gt||or|<string1>|<string2>||<string>`
- [ ] `gt||not|<string>||<integer>`
- [ ] `gt||not|<string>||<string>`
#### `gte`
- [ ] `gte|<string>|<any>`
- [x] `gte|<string>|<integer>`
- [x] `gte|<string>|<string>`
- [x] `gte||and|<string1>|<string2>||<integer>`
- [x] `gte||and|<string1>|<string2>||<string>`
- [x] `gte||or|<string1>|<string2>||<integer>`
- [x] `gte||or|<string1>|<string2>||<string>`
- [ ] `gte||not|<string>||<integer>`
- [ ] `gte||not|<string>||<string>`
### Logical operators
- [x] `and` for joining querys, `and||<query1>||<query2>`
- [x] `and` for joining querys, `and||<query1>||<query2>||<query3>`
- [x] `or` for joining querys, `or||<query1>||<query2>`
- [x] `not` for negating querys, `not||<query>`
- [ ] `and` for combing arguments, see above
- [ ] `or` for combing arguments, see above
- [ ] `not` for negating arguments, see above

### Functions in querys
